### ISSUE TITLE
command line doesn't seem to do anything in 26.0.1

### ISSUE THREAD

**Issue by rjcarr** [actuallymentor/battery#403]
I've used your tool on a couple apple silicon Macs and it's always mostly worked, but I updated one to 26.0.1 (from Sequoia I think) and now the tool isn't working.   The laptop will charge to 100% even if it's maintained much lower, when I stop the maintain and try to start it again it'll always say there was an existing daemon (even when I manually kill the process), and even using the stop charging command doesn't change the status of the charge state.

Is this working for anyone else?

Note I'm using the command line tools only, installed from the curl command, and not the full UI.

**Comment by base47** [comment]
@rjcarr  Open Terminal app and execute

```
battery reinstall
```
This will fix the issue.

**Comment by rjcarr** [comment]
@base47 Thanks for the quick response, but I did a manual reinstall, running the same script the reinstall command does.  It didn't make a difference. However, I just did what you suggested and I'll monitor it over the next couple days and report any problems.  Thanks again!

**Comment by base47** [comment]
@rjcarr Replacing the `/usr/local/bin/battery` script itself is not always enough. When we add new `smc` command variants to the script, we also have to update `/etc/sudoers.d/battery` file. It can be done with both `battery visudo` or `battery reinstall`.

**Comment by rjcarr** [comment]
@base47  I didn't "replace" the script, I "ran" the script as if I were installing it new, just like the "reinstall" command does.  Either way, as I said, I'll report back on my next charge cycle, which is likely today or tomorrow.  Thanks!

**Comment by Rey2319** [comment]
Not working for me either.. any fix yet?

**Comment by T2N-25** [comment]
Me to.. what should i do?

**Comment by base47** [comment]
@Rey2319 @T2N-25 could you please be more specific about what do you see, how it started and which version of macos you are on? Have you tried executing `battery reinstall ` in Terminal app?

**Comment by T2N-25** [comment]
@base47
I'm using Mac OS Tahoe 26.1
I downloaded the CLI version with the command
"curl -s https://raw.githubusercontent.com/actuallymentor/battery/main/setup.sh | bash", 
but I remember getting an error like
"Could not enable service: 125: Domain does not support specified action."
I took that from my search history.
Also, it seems like it's supposed to use battery power, but instead, it's using it through a passthrough.
For reference, I am not using the genuine MacBook charger, but am charging via PD from the Thunderbolt port in the form of a USB C type coming out of the monitor.

**Comment by T2N-25** [comment]
@base47
I tried that command but it's the same.

<img width="70" height="27" alt="Image" src="https://github.com/user-attachments/assets/9ef279f9-6fb9-495c-80b2-12cf9bc36644" />

I'm using the S2725QC monitor. This monitor supports 65W PD charging, but is it because the wattage is insufficient?
macbook pro 14 m4

**Comment by T2N-25** [comment]
@base47 
MacBookPro ~ % battery maintain 40-60
11/13/25-18:44:51 - Killing old maintain process at 35139
11/13/25-18:44:51 - Starting battery maintenance between 40% and 60%
11/13/25-18:44:51 - Writing new setting 40-60 to /Users/kkm/.battery/maintain.percentage
11/13/25-18:44:51 - Maintaining battery between 40% and 60%
11/13/25-18:44:51 - Daemon already exists, checking for differences

**Comment by base47** [comment]
@T2N-25  Not enough info to see whats going on. Try looking into `~/.battery/battery.log`. Maybe you can find some clue in that log file.

What is the output of the following commands on your system? (run in the exact same order. In the end - restart battery app)
```
smc -k CHTE -r
sudo smc -k CHTE -w 01000000
smc -k CHTE -r
sudo smc -k CHTE -w 00000000
smc -k CHTE -r

smc -k CHIE -r
sudo smc -k CHIE -w 08
smc -k CHIE -r
sudo smc -k CHIE -w 00
smc -k CHIE -r

smc -k CH0J -r
sudo smc -k CH0J -w 01
smc -k CH0J -r
sudo smc -k CH0J -w 00
smc -k CH0J -r
```

If any of them ask you for a password try to execute `battery visudo`.

> battery maintain 40-60
> it seems like it's supposed to use battery power, but instead, it's using it through a passthrough

This kind of maintain command works as expected. You are not the first one getting confused with this syntax.

> I am not using the genuine MacBook charger, but am charging via PD from the Thunderbolt port in the form of a USB C type

I'm running M1 pro with Sequoia. It has Magsafe, but I tried charging via USB-C and the app works for me as expected, even though it takes some time to reflect charging status in menubar. It doesn't exclude the possible issue with monitor charging, but makes it less likely.

> "Could not enable service: 125: Domain does not support specified action."

This one is weird. Do you have any security related software installed, like corporate enrolment or something? In any case, the scenario for this error is that you have to launch battery manually after each reboot. Btw, such security software can also forbid the app  to create `/etc/sudoers.d/battery` file, make sure you have this file and the last 3 lines in it are:
```
ALL ALL = NOPASSWD: CHTE
ALL ALL = NOPASSWD: CHIE
ALL ALL = NOPASSWD: CH0J
```

**Comment by rjcarr** [comment]
I thought I'd add an update since my original post.

I've now done both charging events, i.e., charging while using the device and charging while sleeping (lid closed), and in both cases things seem to work well for me and limit the SOC to the maintain setting.  I'm still on 26.0.1 and will likely update to 26.1 soon.

Just wanted to say it wasn't originally working, but either after the reinstall or killing daemons or whatever, it seems to work now.

Thanks!

**Comment by actuallymentor** [comment]
This should be fixed in the [latest release v1.3.1](https://github.com/actuallymentor/battery/releases/tag/v1.3.1). Let me know if you experience more issues.

**Comment by Rey2319** [comment]
After the update, the battery stops charging as soon as I plug in the MagSafe. I reverted to the previous update, but the same thing happens. I’m at 70% battery and it’s not charging at all. I don’t even see the charging symbol, although the MagSafe light turns red. What should I do? I’ve restarted my Mac twice, but the problem persists.

**Comment by base47** [comment]
@Rey2319 
> I’m at 70% battery and it’s not charging at all. I don’t even see the charging symbol, although the MagSafe light turns red. What should I do? I’ve restarted my Mac twice, but the problem persists.

Do this in Terminal following the order:
```
pkill -f "/usr/local/bin/battery"
sudo /usr/local/bin/smc -k CHTE -w 00000000
sudo /usr/local/bin/smc -k CHIE -w 00
sudo /usr/local/bin/smc -k CH0J -w 00
```

**Comment by Rey2319** [comment]
Thanks base47, this solved it.
