### ISSUE TITLE
Macbook pro M1 // stuck at updating... 

### ISSUE THREAD

**Issue by 71m383nd3r** [actuallymentor/battery#49]
**stuck at menubar with message updating....**
<img width="127" alt="Screenshot 2023-02-02 at 13 39 08" src="https://user-images.githubusercontent.com/11781253/216337695-3832f78b-81e8-42ee-9e8a-9b49b5a74e93.png">

more then 20min...

_Macbook Pro 2020 M1, MacOS **Monteray** v12.6.3_
**Battery v1.0.4**

**Comment by actuallymentor** [comment]
I just pushed a update that should fix a few issues, could you try to run `brew reinstall --cask battery` and see if that fixes it?

**Comment by 71m383nd3r** [comment]
<img width="1087" alt="Screenshot 2023-02-04 at 14 15 40" src="https://user-images.githubusercontent.com/11781253/216769838-970f6e81-0904-4bef-b72a-7ad472a4bdf0.png">

>` brew reinstall --cask battery`

<img width="481" alt="Screenshot 2023-02-04 at 14 15 07" src="https://user-images.githubusercontent.com/11781253/216769845-4a726b6b-265a-4c27-aafc-bab0d3899fc0.png">

some other suggestion?
tnx 

I tried as well v1.0.5  - same problem.

**Comment by actuallymentor** [comment]
Ah yes that is a [brew issue](https://github.com/Homebrew/homebrew-cask/issues/140411) that they are trying to fix. Nothing we can do about that for now I'm afraid. Try it again tomorrow.

**Comment by JacksonChen666** [comment]
> Ah yes that is a [brew issue](https://github.com/Homebrew/brew/issues/14504) that they are trying to fix. Nothing we can do about that for now I'm afraid. Try it again tomorrow.

referenced issue is closed, @71m383nd3r try again with `brew reinstall --force battery` (https://github.com/Homebrew/brew/issues/14504#issuecomment-1417747268)

**Comment by 71m383nd3r** [comment]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/11781253/216831123-b67c93b7-c5fd-43ec-a770-e434a8ef9d99.png">
I tried;

 `brew reinstall --force battery`

` brew install --force battery`

still the same problem: `Download failed on Cask 'battery' with message: Download failed: https://github.com/actuallymentor/battery/releases/download/v1.0.5/battery-1.0.5-arm64.dmg`
